spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intecatask
    username: root
    password: zr~R9XBn<n}k
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none