CREATE TABLE `family` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));
 
  CREATE TABLE `father` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BirthDay` DATE NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `PESEL` VARCHAR(11) NOT NULL,
  `SecondName` VARCHAR(45) NOT NULL,
  `FamilyId` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `PESEL_UNIQUE` (`PESEL` ASC) VISIBLE,
  UNIQUE INDEX `FamilyId_UNIQUE` (`FamilyId` ASC) VISIBLE,
  CONSTRAINT `Father_Family_Id_FK`
    FOREIGN KEY (`FamilyId`)
    REFERENCES `family` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `child` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `SecondName` VARCHAR(45) NOT NULL,
  `PESEL` VARCHAR(11) NOT NULL,
  `Sex` VARCHAR(15) NOT NULL,
  `BirthDay` DATE NOT NULL,
  `FamilyId` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `PESEL_UNIQUE` (`PESEL` ASC) VISIBLE,
  INDEX `Child_Family_Id_FK_idx` (`FamilyId` ASC) VISIBLE,
  CONSTRAINT `Child_Family_Id_FK`
    FOREIGN KEY (`FamilyId`)
    REFERENCES `family` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
  